version: '3.8'

services:
  app:
    image: enesuysal/selimsiteadmin:latest
    ports:
      - "3007:3000"
    environment:
      - MONGODB_URI=mongodb+srv://enesuysal:gezEHCEx1Jsxds4X@selimdb.x4clf62.mongodb.net/?retryWrites=true&w=majority&appName=selimDB
      - JWT_SECRET=4706170506b9b6d9cad98c41963ed5fd637c916fe911f3fa49720ecf83be8b746981320d6721b224a8bf4d00fed0d5b0efdd0235a1228d798ca3f121876e352b

  
  selimsite:
    image: enesuysal/selimsite:latest
    container_name: selimsite
    restart: unless-stopped
    ports:
      - "3006:3000"
    environment:
      - MONGODB_URI=mongodb+srv://enesuysal:gezEHCEx1Jsxds4X@selimdb.x4clf62.mongodb.net/?retryWrites=true&w=majority&appName=selimDB
      - JWT_SECRET=4706170506b9b6d9cad98c41963ed5fd637c916fe911f3fa49720ecf83be8b746981320d6721b224a8bf4d00fed0d5b0efdd0235a1228d798ca3f121876e352b
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASS=your_app_password
      - CONTACT_EMAIL=info@selimtesisat.com
      - TELEGRAM_BOT_TOKEN=8217770791:AAF3ivAw-4fTNZVPPhQPb6-Kn2p_L0zkgAU
      - TELEGRAM_GROUP_ID=-4867172864
